CREATE TABLE [dbo].[Employee] (
    [Id]                INT              IDENTITY (1, 1) NOT NULL,
    [EmployeeId]        VARCHAR (50)     NOT NULL,
    [EmployeeName]      VARCHAR (50)     NULL,
    [Gender]            CHAR (1)         NULL,
    [AddressId]         INT              NOT NULL,
    [MaritalStatus]     VARCHAR (50)     NULL,
    [DateOfBirth]       DATETIME         NULL,
    [DateOfJoining]     DATETIME         NULL,
    [BloodGroup]        VARCHAR (50)     NULL,
    [DesignationId]     INT              NOT NULL,
    [DepartmentId]      INT              NOT NULL,
    [Mobile]            VARCHAR (50)     NULL,
    [Aadhar]            VARCHAR (50)     NULL,
    [LocationId]        INT              NOT NULL,
    [UAN]               VARCHAR (50)     NULL,
    [ESI]               VARCHAR (50)     NULL,
    [BankId]            INT              NOT NULL,
    [BankAccountNumber] VARCHAR (50)     NOT NULL,
    [ModifiedDate]      DATETIME         CONSTRAINT [DF_Employee_ModifiedDate] DEFAULT (getutcdate()) NOT NULL,
    [ModifiedBy]        UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_Employee] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Employee_Address] FOREIGN KEY ([AddressId]) REFERENCES [dbo].[Address] ([Id]),
    CONSTRAINT [FK_Employee_BankDetails] FOREIGN KEY ([BankId]) REFERENCES [dbo].[BankDetails] ([Id]),
    CONSTRAINT [FK_Employee_Department] FOREIGN KEY ([DepartmentId]) REFERENCES [dbo].[Department] ([Id]),
    CONSTRAINT [FK_Employee_Designation] FOREIGN KEY ([DesignationId]) REFERENCES [dbo].[Designation] ([Id]),
    CONSTRAINT [FK_Employee_Location] FOREIGN KEY ([LocationId]) REFERENCES [dbo].[Location] ([Id]),
    CONSTRAINT [FK_Employee_User] FOREIGN KEY ([ModifiedBy]) REFERENCES [dbo].[User] ([UserId])
);

